name: Prerelease
env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
on:
  push:
    branches:
      - main
jobs:
  prerelease:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'no-release') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - name: Setup git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build
        run: npm run setup
      - name: Disable branch protection
        continue-on-error: true
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/${{ github.repository }}/branches/main/protection
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # In order to disable common version line remove the --force-publish flag in lerna command below
      - name: Prerelease
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=beta --include-merged-tags --force-publish --yes
      - name: Enable branch protection
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/${{ github.repository }}/branches/main/protection
          required_pull_request_reviews: |
            dismiss_stale_reviews: true
            required_approving_review_count: 2
          required_status_checks: |
            strict: true
            checks:
              - context: 'Setup, Build, Lint and Test'
          enforce_admins: true
          restrictions: 'null'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
          npx lerna publish from-git --dist-tag=next --yes
      - name: Unset Git User
        run: |
          git config --unset user.name
          git config --unset user.email
